### ISSUE TITLE
编码错误

### ISSUE THREAD

**Issue by aaaisan** [HisAtri/LrcApi#102]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

一切挺正好，返回也是200，但是没结果，看日志说是utf-8编码错误？
![屏幕截图 2024-11-29 110530](https://github.com/user-attachments/assets/c1c8d3fb-2092-4653-9add-b3788e7557f5)

iphone返回：
![IMG_1683](https://github.com/user-attachments/assets/476905f0-a7c1-408d-8da7-41bb7bc1b4e0)

### 系统信息

群晖 docker

**Comment by HisAtri** [comment]
Duplicate #65 

浏览器清空Cookie
