### ISSUE TITLE
chore: docker构建流程存在异常 && deploy应采用更健壮的HTTPServer

### ISSUE THREAD

**Issue by Aberstone** [HisAtri/LrcApi#17]
### 提交Feature之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。
- [X] 不是所有的Feature都会被接受，合理且详细的Feature有更高的概率被接受。

### 问题描述

1. `.dockerignore` 文件配置错误，应该为 `.dockerignore` 而不是 `dockerignore`
2. 代码使用了 `python3.10+` 支持的 `match...case...` 特性，但基础镜像为 `3.9.17` 版本
3. 服务部署建议采用兼容支持 `wsgi` 的 `http` 服务器替换 `flash` 自带的 `DebugServer`

**Comment by Aberstone** [comment]
[https://github.com/Aberstone/LrcApi/blob/chore/add_gunicorn/Dockerfile.gunicorn](url)
重新使用gunicorn构建的dockerfile已附带

**Comment by HisAtri** [comment]
## Docker
此方案之前是为了用户自行搭建而写的参考，由于使用较少很久没有维护，以后可以考虑补充一下~。
因为部分模块需要gcc编译，我目前使用Buildx多级构建，基于alpine-py3.10镜像。
## WSGI服务
项目使用的不是自带的DebugServer，而是Waitress WSGI。
不考虑gunicorn的原因：
1.不支持Windows
2.此项目倾向私有而非公开部署，不是特别需要高并发性能，但是要着重考虑低配置性能
3.Waitress部署调试简单且低负载下性能与Gunicorn相差无几
综合考虑下来，我还是认为使用Waitress作为WSGI更加合适。

**Comment by Aberstone** [comment]
> ## WSGI服务
> 项目使用的不是自带的DebugServer，而是Waitress WSGI。 不考虑gunicorn的原因： 1.不支持Windows 2.此项目倾向私有而非公开部署，不是特别需要高并发性能，但是要着重考虑低配置性能 3.Waitress部署调试简单且低负载下性能与Gunicorn相差无几 综合考虑下来，我还是认为使用Waitress作为WSGI更加合适。

是我眼睛瞎了没看到Waitress的serve;
