### ISSUE TITLE
windows安装Navidrome获取不到文件路径同名的 .lrc 文件

### ISSUE THREAD

**Issue by hiseab** [HisAtri/LrcApi#22]
### 提交Feature之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。
- [X] 不是所有的Feature都会被接受，合理且详细的Feature有更高的概率被接受。

### 问题描述

windows安装Navidrome获取不到文件路径同名的 .lrc 文件

### 解决方案

判断一下路径是否带有盘符，如果带就去掉

**Comment by HisAtri** [comment]
方便提供一下具体的请求吗？

**Comment by hiseab** [comment]
jsonapi?title=黄昏&artist=周传雄&album=我在身边新加坡演唱会&offset=0&limit=1&path=D%3A%5CMUSIC%5C中文音乐%5C周传雄%5C周传雄+-+我在身边新加坡演唱会%5CCD2%5C周传雄+-+黄昏.flac&duration=389

**Comment by HisAtri** [comment]
该问题与请求路径中的"+"处理有关，按照URL编码规范，"+"应该被编码为"%2B"，而" "（空格）应该被编码为"%20"，这个URL参数里的"+"没有被正确编码，所以被解码成空格。

**Comment by HisAtri** [comment]
该问题为请求参数不符合W3C及URL编码规范导致，非服务端问题。
