### ISSUE TITLE
docker部署后会一直存在100多KB的上传流量，即使在接口未使用的时候

### ISSUE THREAD

**Issue by chizhiao** [HisAtri/LrcApi#45]
### 提交Issue之前，你应当知道：

- [x] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

docker部署会一直存在100多KB的上传流量，即使在接口未使用的时候，请问这个上传主要是在运行什么功能吗，按照我的理解应该仅在使用的时候调用了相应的接口才会产生上行流量，但是即使在未使用的时候也在持续产生上传流量

### 系统信息

群晖7.0.1 docker部署最新版

**Comment by HisAtri** [comment]
我在本地部署了最新的Docker，一段时间内似乎没有观察到类似的情况。你可以尝试排查：
1. 是否统计的是物理网卡的流量；Linux系统内的一些通讯会在部分虚拟网卡上产生流量，这部分容易和真实的流量混淆
2. 是否有其他人访问该服务

**Comment by chizhiao** [comment]
> 我在本地部署了最新的Docker，一段时间内似乎没有观察到类似的情况。你可以尝试排查：
> 
> 1. 是否统计的是物理网卡的流量;Linux系统内的一些通讯会在部分虚拟网卡上产生流量，这部分容易和真实的流量混淆
> 2. 是否有其他人访问该服务

流量统计应该没有问题，关掉了其他容器，群晖显示的流量和iKuai中显示的流量一样，打开这个容器就有关掉就没有，会一直持续虽然不大大概一下午一晚上能有一两个G，我再尝试一下修改鉴权key再观察一下

**Comment by chizhiao** [comment]
> 我在本地部署了最新的Docker，一段时间内似乎没有观察到类似的情况。你可以尝试排查：
> 
> 1. 是否统计的是物理网卡的流量；Linux系统内的一些通讯会在部分虚拟网卡上产生流量，这部分容易和真实的流量混淆
> 2. 是否有其他人访问该服务

删除了原本的容器，重新拉取构建似乎一切正常了，可能是之前版本然后升级有什么bug
