### ISSUE TITLE
linux版本二进制文件无法运行报错

### ISSUE THREAD

**Issue by maytom2016** [HisAtri/LrcApi#47]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

版本1.5.3，linux架构如下文件运行有问题
arm7l
./lrcapi: cannot execute: required file not found
x86_64
-bash: ./lrcapi: No such file or directory

## x86_64环境下：
root@dokcer:~# ls|grep lrc
lrcapi
root@dokcer:~# ./lrcapi 
-bash: ./lrcapi: No such file or directory
root@dokcer:~# uname -a
Linux dokcer 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64 GNU/Linux
root@dokcer:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
## armv7l环境下（termux app）：
~/lrcapi $ uname -a
Linux localhost 3.4.113-perf-g9cd90d33e3a #1 SMP PREEMPT Wed Oct 19 16:15:37 CST 2022 armv7l Android
~/lrcapi $ ./lrcapi
bash: ./lrcapi: cannot execute: required file not found
~/lrcapi $ ./lrcapi --port 8080 --auth abc
bash: ./lrcapi: cannot execute: required file not found

### 系统信息

debian11&&android

### 补充信息

python对目录处理有问题

**Comment by SatoMatsuzaka** [comment]
v1.5.3之后的打包流程存在问题 #41

**Comment by HisAtri** [comment]
#50 修复问题
