### ISSUE TITLE
可否增加API获取到的歌词直接写入音乐文件标签

### ISSUE THREAD

**Issue by taolile** [HisAtri/LrcApi#5]
### 提交Feature之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。
- [X] 不是所有的Feature都会被接受，合理且详细的Feature有更高的概率被接受。

### 问题描述

每次都要重新获取歌词，而且获取的比较慢，建议把API获取到的歌词直接写入音乐文件标签。

### 解决方案

可以在音流APP上api获取到的歌词写入到音乐源文件标签，比如在音流APP歌词显示哪里添加一个歌词嵌入按钮。

**Comment by HisAtri** [comment]
#6 初步完成

**Comment by SatoMatsuzaka** [comment]
FLAC/ID3v2/VorbisComment 标签的修改功能已测试
[API接口](https://github.com/HisAtri/LrcApi#tag%E4%BF%AE%E6%94%B9%E6%8E%A5%E5%8F%A3)
