### ISSUE TITLE
docker部署的服务请求封面api会自动重定向

### ISSUE THREAD

**Issue by zhangjh** [HisAtri/LrcApi#51]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

使用docker部署的api服务：`docker run -d -p 28883:28883 -v /root/music:/music hisatri/lrcapi:latest`
在请求歌词api时正常，但是在请求封面api时异常，会重定向到：
`https://api.lrc.cx/cover/album/title=xxx&artist=xxx`
原始请求是`http://ip:port/api/v1/cover/album?title=xxx&artist=xxx`

### 系统信息

ubuntu 22.04

**Comment by zhangjh** [comment]
简单看了一下代码，这算是个鸡毛的开源项目，就是起了一个HTTP server的皮。。。
最后所有的逻辑都是发起了HTTP请求，请求固定的搜索服务，就是重定向到`cn.lrc.cx:880`....

**Comment by HisAtri** [comment]
重定向是正常行为，因为封面获取逻辑依靠现成的NodeJS项目，不便于打包Docker，并且也没必要重复造轮子。
还有，`简单看了一下代码`我是信的，你看的确实够简单。
