### ISSUE TITLE
为什么我按照文档拉取镜像并启动容器后在音流里面调用接口，无法获取歌手和封面图片呢，是这个api失效了吗

### ISSUE THREAD

**Issue by dajiangfu** [HisAtri/LrcApi#52]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

为什么我按照文档拉取镜像并启动容器后在音流里面调用接口，无法获取歌手和封面图片呢，是这个api失效了吗，我的命令行：
docker run -d -p 28883:28883 -v /mnt/nvme1-1/音乐:/mnt/nvme1-1/音乐 -e API_AUTH=xiaohaha1523 hisatri/lrcapi:latest

### 系统信息

openwrt

**Comment by fightroad** [comment]
我发现也是   降级到1.5.2 试试

**Comment by Aberstone** [comment]
可以提供下你在音流中调用 LrcApi 的哪些接口；以及报错的日志吗。
docker 日志 可以通过 docker logs <container_name/container_ID> 获取。

**Comment by HisAtri** [comment]
公共服务器的数据库炸了导致的。
得看能不能用Python做个封面查询接口放这个项目里。。。
#51

**Comment by Aberstone** [comment]
> 公共服务器的数据库炸了导致的。 得看能不能用Python做个封面查询接口放这个项目里。。。 #51

现在用的哪个node服务提供的cover获取啊。网易云那个吗

**Comment by HisAtri** [comment]
> > 公共服务器的数据库炸了导致的。 得看能不能用Python做个封面查询接口放这个项目里。。。 #51
> 
> 现在用的哪个node服务提供的cover获取啊。网易云那个吗

是的

**Comment by Temoa** [comment]
> 我发现也是 降级到1.5.2 试试

我这边也是这样，1.5.4和1.5.3都不行，1.5.2正常

**Comment by Temoa** [comment]
> 可以提供下你在音流中调用 LrcApi 的哪些接口；以及报错的日志吗。 docker 日志 可以通过 docker logs <container_name/container_ID> 获取。

使用最新版本 1.5.4，没有看到的错误日志。

```txt
2024-06-11 03:50:27,440 - INFO - 正在启动服务器
2024-06-11 03:50:27,440 - INFO - 正在检查更新，当前版本
2024-06-11 03:50:27,447 - INFO - Serving on http://0.0.0.0:28883
2024-06-11 03:50:27,817 - INFO - 当前已是最新版本
```

在最新版“音流” APP 中，自定义 API 设置 -> 歌词接口 -> 上次请求信息中能看请求的响应体，但是在播放界面->歌词没有显示歌词。

使用 1.5.2 就正常了。

**Comment by HisAtri** [comment]
> 使用最新版本 1.5.4，没有看到的错误日志。
> 
> ```
> 2024-06-11 03:50:27,440 - INFO - 正在启动服务器
> 2024-06-11 03:50:27,440 - INFO - 正在检查更新，当前版本
> 2024-06-11 03:50:27,447 - INFO - Serving on http://0.0.0.0:28883
> 2024-06-11 03:50:27,817 - INFO - 当前已是最新版本
> ```
> 
> 在最新版“音流” APP 中，自定义 API 设置 -> 歌词接口 -> 上次请求信息中能看请求的响应体，但是在播放界面->歌词没有显示歌词。
> 
> 使用 1.5.2 就正常了。

wtf...？

**Comment by sayggtome** [comment]
我是歌词都能正常获取，封面都不行

**Comment by EternalSunLhx** [comment]
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/c14a85b5-48fe-439d-8ba8-8606d26388dc">
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/41ee180a-3ef1-4efa-bdf7-d2f8f713f38d">
最新版本炸了

**Comment by hikasky** [comment]
同樣docker 使用1.5.4版本 搜索歌詞無响應, 降至1.5.2 就正常了
