### ISSUE TITLE
歌词能保存到本地目录

### ISSUE THREAD

**Issue by sanchidr** [HisAtri/LrcApi#57]
### 提交Feature之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。
- [X] 不是所有的Feature都会被接受，合理且详细的Feature有更高的概率被接受。

### 问题描述

如果歌词能保存到docker本地映射的目录最好了，这样不用每次都要再次请求。

### 解决方案

如果歌词能保存到docker本地映射的目录最好了，这样不用每次都要再次请求。

**Comment by HisAtri** [comment]
有缓存机制的
