### ISSUE TITLE
request song list

### ISSUE THREAD

**Issue by JohnStyleZ** [HisAtri/LrcApi#60]
### 提交Feature之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。
- [X] 不是所有的Feature都会被接受，合理且详细的Feature有更高的概率被接受。

### 问题描述

可以request 歌曲嗎？ 就是如果我搜一個歌名或歌手名就會返回一個list， 然後就可以從中選擇歌詞就像lrclib一樣可以search

**Comment by HisAtri** [comment]
使用`/jsonapi`接口可以批量搜索
