### ISSUE TITLE
流音封面接口covers与lrcapi的cover接口不一致，怎么破呀

### ISSUE THREAD

**Issue by lz732895965** [HisAtri/LrcApi#61]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

流音封面接口covers与lrcapi的cover接口不一致，怎么破呀

### 请求与响应

cover

### 日志文件

-

### 系统信息

iOS

**Comment by HisAtri** [comment]
直接填就好了，URL不一样不影响
