### ISSUE TITLE
cn.lrc.cx不能用了

### ISSUE THREAD

**Issue by vvxu** [HisAtri/LrcApi#66]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

提示Connection to cn.lrc.cx 错误。

### 系统信息

debian12，python部署

**Comment by HisAtri** [comment]
已修复
