### ISSUE TITLE
docker需要有翻的环境，才能搜索到歌。

### ISSUE THREAD

**Issue by rivergod520** [HisAtri/LrcApi#70]
### 提交Feature之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。
- [X] 不是所有的Feature都会被接受，合理且详细的Feature有更高的概率被接受。

### 问题描述

docker需要有翻的环境，才能搜索到歌。

**Comment by HisAtri** [comment]
所使用的接口均为国内服务，我没有观察到类似情况

**Comment by HisAtri** [comment]
未复现

**Comment by HisAtri** [comment]
未复现该情况
