### ISSUE TITLE
使用群辉docker部署lrcapi，音流搜索歌词无反应

### ISSUE THREAD

**Issue by qhly2010** [HisAtri/LrcApi#86]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

使用群辉docker部署lrcapi，版本1.5.6，网页能正常访问192.168.101.201:28883，如图：
![06](https://github.com/user-attachments/assets/466f2fd1-2714-450e-b47e-d14c269e72e2)

音流歌词api地址设置为192.168.101.201/jsonapi,搜索歌词时报错，日志如下
![07](https://github.com/user-attachments/assets/591ab718-3aaa-46be-9cc9-9726a13ec150)

### 日志文件

[log.txt](https://github.com/user-attachments/files/17391839/log.txt)

### 系统信息

使用群辉ds220+,docker部署lrcapi,应该是x86架构

**Comment by qhly2010** [comment]
音流歌词api地址设置为192.168.101.201/lyrics,歌词能搜索，但是只显示一个歌词，无法像jsonapi那样可以批量搜索，可左右滑动选择正确匹配的歌词

**Comment by HisAtri** [comment]
确认了大概的原因，修了一下，等测试
